server:
  port: 8080
  http2:
   enabled: true

spring:
 data:
  mongodb:
   database: posts
   host: localhost
   port: 27017
 servlet:
  multipart:
   max-file-size: 2MB

logging:
 pattern:
  console: -%clr(%d{yyyy-MM-dd HH:mm:ss.SSS}){faint} %clr(%5p) %clr(${PID:}){magenta} %clr(---){faint} %clr([%15.15t]){faint} %clr(%-40.40logger{39}){cyan} %clr(:){faint} %clr(%X{correlation_id}){red} %m%n%wEx
# level:
#  org:
#   springframework:
#    data:
#     mongodb:
#      core:
#       MongoTemplate: DEBUG


graphql:
 servlet:
  mapping: /graphql
  enabled: true
  corsEnabled: true
  maxQueryDepth: 100
  exception-handlers-enabled: true
  tracingEnabled: true
 playground:
  headers:
   Authorization: Bearer TOKEN
   user_id: SomeUSERID
  settings:
   schema:
    polling:
     interval: 60000
#  tabs:
#   - name: Bank account sample query
#     query: classpath:playground/bank_account.graphql
#     variables: classpath:playground/bank_account_variables.json
#voyager:
# enabled: true